// Stubs for the temporal_rs C ABI (V8's JS Temporal proposal backend).
//
// The Windows v8_monolith.lib was built with V8's default gn config, where
// the Temporal implementation lives in a separate Rust static library
// (//third_party/temporal_rs) that is NOT merged into the monolith. None of
// its 258 entry points are reachable unless JS code actually uses the
// Temporal API, so abort()-ing stubs are enough to satisfy the linker.
// (The Linux libv8_monolith.a does not reference these symbols.)
#include <stdlib.h>

void temporal_rs_AnyCalendarKind_get_for_str(void) { abort(); }
void temporal_rs_AnyCalendarKind_parse_temporal_calendar_string(void) { abort(); }
void temporal_rs_Calendar_identifier(void) { abort(); }
void temporal_rs_Calendar_kind(void) { abort(); }
void temporal_rs_Duration_abs(void) { abort(); }
void temporal_rs_Duration_add(void) { abort(); }
void temporal_rs_Duration_clone(void) { abort(); }
void temporal_rs_Duration_compare_with_provider(void) { abort(); }
void temporal_rs_Duration_create(void) { abort(); }
void temporal_rs_Duration_days(void) { abort(); }
void temporal_rs_Duration_destroy(void) { abort(); }
void temporal_rs_Duration_from_partial_duration(void) { abort(); }
void temporal_rs_Duration_from_utf16(void) { abort(); }
void temporal_rs_Duration_from_utf8(void) { abort(); }
void temporal_rs_Duration_hours(void) { abort(); }
void temporal_rs_Duration_microseconds(void) { abort(); }
void temporal_rs_Duration_milliseconds(void) { abort(); }
void temporal_rs_Duration_minutes(void) { abort(); }
void temporal_rs_Duration_months(void) { abort(); }
void temporal_rs_Duration_nanoseconds(void) { abort(); }
void temporal_rs_Duration_negated(void) { abort(); }
void temporal_rs_Duration_round_with_provider(void) { abort(); }
void temporal_rs_Duration_seconds(void) { abort(); }
void temporal_rs_Duration_sign(void) { abort(); }
void temporal_rs_Duration_subtract(void) { abort(); }
void temporal_rs_Duration_to_string(void) { abort(); }
void temporal_rs_Duration_total_with_provider(void) { abort(); }
void temporal_rs_Duration_weeks(void) { abort(); }
void temporal_rs_Duration_years(void) { abort(); }
void temporal_rs_I128Nanoseconds_is_valid(void) { abort(); }
void temporal_rs_Instant_add(void) { abort(); }
void temporal_rs_Instant_clone(void) { abort(); }
void temporal_rs_Instant_compare(void) { abort(); }
void temporal_rs_Instant_destroy(void) { abort(); }
void temporal_rs_Instant_epoch_milliseconds(void) { abort(); }
void temporal_rs_Instant_epoch_nanoseconds(void) { abort(); }
void temporal_rs_Instant_from_epoch_milliseconds(void) { abort(); }
void temporal_rs_Instant_from_utf16(void) { abort(); }
void temporal_rs_Instant_from_utf8(void) { abort(); }
void temporal_rs_Instant_round(void) { abort(); }
void temporal_rs_Instant_since(void) { abort(); }
void temporal_rs_Instant_subtract(void) { abort(); }
void temporal_rs_Instant_to_ixdtf_string_with_provider(void) { abort(); }
void temporal_rs_Instant_to_zoned_date_time_iso_with_provider(void) { abort(); }
void temporal_rs_Instant_try_new(void) { abort(); }
void temporal_rs_Instant_until(void) { abort(); }
void temporal_rs_OwnedRelativeTo_from_utf16_with_provider(void) { abort(); }
void temporal_rs_OwnedRelativeTo_from_utf8_with_provider(void) { abort(); }
void temporal_rs_ParsedDate_destroy(void) { abort(); }
void temporal_rs_ParsedDate_from_utf16(void) { abort(); }
void temporal_rs_ParsedDate_from_utf8(void) { abort(); }
void temporal_rs_ParsedDate_month_day_from_utf16(void) { abort(); }
void temporal_rs_ParsedDate_month_day_from_utf8(void) { abort(); }
void temporal_rs_ParsedDate_year_month_from_utf16(void) { abort(); }
void temporal_rs_ParsedDate_year_month_from_utf8(void) { abort(); }
void temporal_rs_ParsedDateTime_destroy(void) { abort(); }
void temporal_rs_ParsedDateTime_from_utf16(void) { abort(); }
void temporal_rs_ParsedDateTime_from_utf8(void) { abort(); }
void temporal_rs_ParsedZonedDateTime_destroy(void) { abort(); }
void temporal_rs_ParsedZonedDateTime_from_utf16_with_provider(void) { abort(); }
void temporal_rs_ParsedZonedDateTime_from_utf8_with_provider(void) { abort(); }
void temporal_rs_PlainDate_add(void) { abort(); }
void temporal_rs_PlainDate_calendar(void) { abort(); }
void temporal_rs_PlainDate_clone(void) { abort(); }
void temporal_rs_PlainDate_compare(void) { abort(); }
void temporal_rs_PlainDate_day(void) { abort(); }
void temporal_rs_PlainDate_day_of_week(void) { abort(); }
void temporal_rs_PlainDate_day_of_year(void) { abort(); }
void temporal_rs_PlainDate_days_in_month(void) { abort(); }
void temporal_rs_PlainDate_days_in_week(void) { abort(); }
void temporal_rs_PlainDate_days_in_year(void) { abort(); }
void temporal_rs_PlainDate_destroy(void) { abort(); }
void temporal_rs_PlainDate_epoch_ms_for_utc(void) { abort(); }
void temporal_rs_PlainDate_equals(void) { abort(); }
void temporal_rs_PlainDate_era(void) { abort(); }
void temporal_rs_PlainDate_era_year(void) { abort(); }
void temporal_rs_PlainDate_from_parsed(void) { abort(); }
void temporal_rs_PlainDate_from_partial(void) { abort(); }
void temporal_rs_PlainDate_in_leap_year(void) { abort(); }
void temporal_rs_PlainDate_month(void) { abort(); }
void temporal_rs_PlainDate_month_code(void) { abort(); }
void temporal_rs_PlainDate_months_in_year(void) { abort(); }
void temporal_rs_PlainDate_since(void) { abort(); }
void temporal_rs_PlainDate_subtract(void) { abort(); }
void temporal_rs_PlainDate_to_ixdtf_string(void) { abort(); }
void temporal_rs_PlainDate_to_plain_date_time(void) { abort(); }
void temporal_rs_PlainDate_to_plain_month_day(void) { abort(); }
void temporal_rs_PlainDate_to_plain_year_month(void) { abort(); }
void temporal_rs_PlainDate_to_zoned_date_time_with_provider(void) { abort(); }
void temporal_rs_PlainDate_try_new(void) { abort(); }
void temporal_rs_PlainDate_until(void) { abort(); }
void temporal_rs_PlainDate_week_of_year(void) { abort(); }
void temporal_rs_PlainDate_with(void) { abort(); }
void temporal_rs_PlainDate_with_calendar(void) { abort(); }
void temporal_rs_PlainDate_year(void) { abort(); }
void temporal_rs_PlainDate_year_of_week(void) { abort(); }
void temporal_rs_PlainDateTime_add(void) { abort(); }
void temporal_rs_PlainDateTime_calendar(void) { abort(); }
void temporal_rs_PlainDateTime_clone(void) { abort(); }
void temporal_rs_PlainDateTime_compare(void) { abort(); }
void temporal_rs_PlainDateTime_day(void) { abort(); }
void temporal_rs_PlainDateTime_day_of_week(void) { abort(); }
void temporal_rs_PlainDateTime_day_of_year(void) { abort(); }
void temporal_rs_PlainDateTime_days_in_month(void) { abort(); }
void temporal_rs_PlainDateTime_days_in_week(void) { abort(); }
void temporal_rs_PlainDateTime_days_in_year(void) { abort(); }
void temporal_rs_PlainDateTime_destroy(void) { abort(); }
void temporal_rs_PlainDateTime_epoch_ms_for_utc(void) { abort(); }
void temporal_rs_PlainDateTime_equals(void) { abort(); }
void temporal_rs_PlainDateTime_era(void) { abort(); }
void temporal_rs_PlainDateTime_era_year(void) { abort(); }
void temporal_rs_PlainDateTime_from_parsed(void) { abort(); }
void temporal_rs_PlainDateTime_from_partial(void) { abort(); }
void temporal_rs_PlainDateTime_hour(void) { abort(); }
void temporal_rs_PlainDateTime_in_leap_year(void) { abort(); }
void temporal_rs_PlainDateTime_microsecond(void) { abort(); }
void temporal_rs_PlainDateTime_millisecond(void) { abort(); }
void temporal_rs_PlainDateTime_minute(void) { abort(); }
void temporal_rs_PlainDateTime_month(void) { abort(); }
void temporal_rs_PlainDateTime_month_code(void) { abort(); }
void temporal_rs_PlainDateTime_months_in_year(void) { abort(); }
void temporal_rs_PlainDateTime_nanosecond(void) { abort(); }
void temporal_rs_PlainDateTime_round(void) { abort(); }
void temporal_rs_PlainDateTime_second(void) { abort(); }
void temporal_rs_PlainDateTime_since(void) { abort(); }
void temporal_rs_PlainDateTime_subtract(void) { abort(); }
void temporal_rs_PlainDateTime_to_ixdtf_string(void) { abort(); }
void temporal_rs_PlainDateTime_to_plain_date(void) { abort(); }
void temporal_rs_PlainDateTime_to_plain_time(void) { abort(); }
void temporal_rs_PlainDateTime_to_zoned_date_time_with_provider(void) { abort(); }
void temporal_rs_PlainDateTime_try_new(void) { abort(); }
void temporal_rs_PlainDateTime_until(void) { abort(); }
void temporal_rs_PlainDateTime_week_of_year(void) { abort(); }
void temporal_rs_PlainDateTime_with(void) { abort(); }
void temporal_rs_PlainDateTime_with_calendar(void) { abort(); }
void temporal_rs_PlainDateTime_with_time(void) { abort(); }
void temporal_rs_PlainDateTime_year(void) { abort(); }
void temporal_rs_PlainDateTime_year_of_week(void) { abort(); }
void temporal_rs_PlainMonthDay_calendar(void) { abort(); }
void temporal_rs_PlainMonthDay_clone(void) { abort(); }
void temporal_rs_PlainMonthDay_day(void) { abort(); }
void temporal_rs_PlainMonthDay_destroy(void) { abort(); }
void temporal_rs_PlainMonthDay_epoch_ms_for_utc(void) { abort(); }
void temporal_rs_PlainMonthDay_equals(void) { abort(); }
void temporal_rs_PlainMonthDay_from_parsed(void) { abort(); }
void temporal_rs_PlainMonthDay_from_partial(void) { abort(); }
void temporal_rs_PlainMonthDay_month_code(void) { abort(); }
void temporal_rs_PlainMonthDay_to_ixdtf_string(void) { abort(); }
void temporal_rs_PlainMonthDay_to_plain_date(void) { abort(); }
void temporal_rs_PlainMonthDay_try_new_with_overflow(void) { abort(); }
void temporal_rs_PlainMonthDay_with(void) { abort(); }
void temporal_rs_PlainTime_add(void) { abort(); }
void temporal_rs_PlainTime_clone(void) { abort(); }
void temporal_rs_PlainTime_compare(void) { abort(); }
void temporal_rs_PlainTime_destroy(void) { abort(); }
void temporal_rs_PlainTime_epoch_ms_for_utc(void) { abort(); }
void temporal_rs_PlainTime_equals(void) { abort(); }
void temporal_rs_PlainTime_from_partial(void) { abort(); }
void temporal_rs_PlainTime_from_utf16(void) { abort(); }
void temporal_rs_PlainTime_from_utf8(void) { abort(); }
void temporal_rs_PlainTime_hour(void) { abort(); }
void temporal_rs_PlainTime_microsecond(void) { abort(); }
void temporal_rs_PlainTime_millisecond(void) { abort(); }
void temporal_rs_PlainTime_minute(void) { abort(); }
void temporal_rs_PlainTime_nanosecond(void) { abort(); }
void temporal_rs_PlainTime_round(void) { abort(); }
void temporal_rs_PlainTime_second(void) { abort(); }
void temporal_rs_PlainTime_since(void) { abort(); }
void temporal_rs_PlainTime_subtract(void) { abort(); }
void temporal_rs_PlainTime_to_ixdtf_string(void) { abort(); }
void temporal_rs_PlainTime_try_new(void) { abort(); }
void temporal_rs_PlainTime_until(void) { abort(); }
void temporal_rs_PlainTime_with(void) { abort(); }
void temporal_rs_PlainYearMonth_add(void) { abort(); }
void temporal_rs_PlainYearMonth_calendar(void) { abort(); }
void temporal_rs_PlainYearMonth_clone(void) { abort(); }
void temporal_rs_PlainYearMonth_compare(void) { abort(); }
void temporal_rs_PlainYearMonth_days_in_month(void) { abort(); }
void temporal_rs_PlainYearMonth_days_in_year(void) { abort(); }
void temporal_rs_PlainYearMonth_destroy(void) { abort(); }
void temporal_rs_PlainYearMonth_epoch_ms_for_utc(void) { abort(); }
void temporal_rs_PlainYearMonth_equals(void) { abort(); }
void temporal_rs_PlainYearMonth_era(void) { abort(); }
void temporal_rs_PlainYearMonth_era_year(void) { abort(); }
void temporal_rs_PlainYearMonth_from_parsed(void) { abort(); }
void temporal_rs_PlainYearMonth_from_partial(void) { abort(); }
void temporal_rs_PlainYearMonth_in_leap_year(void) { abort(); }
void temporal_rs_PlainYearMonth_month(void) { abort(); }
void temporal_rs_PlainYearMonth_month_code(void) { abort(); }
void temporal_rs_PlainYearMonth_months_in_year(void) { abort(); }
void temporal_rs_PlainYearMonth_since(void) { abort(); }
void temporal_rs_PlainYearMonth_subtract(void) { abort(); }
void temporal_rs_PlainYearMonth_to_ixdtf_string(void) { abort(); }
void temporal_rs_PlainYearMonth_to_plain_date(void) { abort(); }
void temporal_rs_PlainYearMonth_try_new_with_overflow(void) { abort(); }
void temporal_rs_PlainYearMonth_until(void) { abort(); }
void temporal_rs_PlainYearMonth_with(void) { abort(); }
void temporal_rs_PlainYearMonth_year(void) { abort(); }
void temporal_rs_Provider_destroy(void) { abort(); }
void temporal_rs_Provider_empty(void) { abort(); }
void temporal_rs_Provider_new_zoneinfo64(void) { abort(); }
void temporal_rs_TimeZone_identifier_with_provider(void) { abort(); }
void temporal_rs_TimeZone_try_from_identifier_str_with_provider(void) { abort(); }
void temporal_rs_TimeZone_try_from_offset_str(void) { abort(); }
void temporal_rs_TimeZone_try_from_str_with_provider(void) { abort(); }
void temporal_rs_TimeZone_utc_with_provider(void) { abort(); }
void temporal_rs_TimeZone_zero(void) { abort(); }
void temporal_rs_ZonedDateTime_add_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_calendar(void) { abort(); }
void temporal_rs_ZonedDateTime_clone(void) { abort(); }
void temporal_rs_ZonedDateTime_compare_instant(void) { abort(); }
void temporal_rs_ZonedDateTime_day(void) { abort(); }
void temporal_rs_ZonedDateTime_day_of_week(void) { abort(); }
void temporal_rs_ZonedDateTime_day_of_year(void) { abort(); }
void temporal_rs_ZonedDateTime_days_in_month(void) { abort(); }
void temporal_rs_ZonedDateTime_days_in_week(void) { abort(); }
void temporal_rs_ZonedDateTime_days_in_year(void) { abort(); }
void temporal_rs_ZonedDateTime_destroy(void) { abort(); }
void temporal_rs_ZonedDateTime_epoch_milliseconds(void) { abort(); }
void temporal_rs_ZonedDateTime_epoch_nanoseconds(void) { abort(); }
void temporal_rs_ZonedDateTime_equals_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_era(void) { abort(); }
void temporal_rs_ZonedDateTime_era_year(void) { abort(); }
void temporal_rs_ZonedDateTime_from_parsed_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_from_partial_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_get_time_zone_transition_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_hour(void) { abort(); }
void temporal_rs_ZonedDateTime_hours_in_day_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_in_leap_year(void) { abort(); }
void temporal_rs_ZonedDateTime_microsecond(void) { abort(); }
void temporal_rs_ZonedDateTime_millisecond(void) { abort(); }
void temporal_rs_ZonedDateTime_minute(void) { abort(); }
void temporal_rs_ZonedDateTime_month(void) { abort(); }
void temporal_rs_ZonedDateTime_month_code(void) { abort(); }
void temporal_rs_ZonedDateTime_months_in_year(void) { abort(); }
void temporal_rs_ZonedDateTime_nanosecond(void) { abort(); }
void temporal_rs_ZonedDateTime_offset(void) { abort(); }
void temporal_rs_ZonedDateTime_offset_nanoseconds(void) { abort(); }
void temporal_rs_ZonedDateTime_round_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_second(void) { abort(); }
void temporal_rs_ZonedDateTime_since_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_start_of_day_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_subtract_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_timezone(void) { abort(); }
void temporal_rs_ZonedDateTime_to_instant(void) { abort(); }
void temporal_rs_ZonedDateTime_to_ixdtf_string_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_to_plain_date(void) { abort(); }
void temporal_rs_ZonedDateTime_to_plain_datetime(void) { abort(); }
void temporal_rs_ZonedDateTime_to_plain_time(void) { abort(); }
void temporal_rs_ZonedDateTime_try_new_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_until_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_week_of_year(void) { abort(); }
void temporal_rs_ZonedDateTime_with_calendar(void) { abort(); }
void temporal_rs_ZonedDateTime_with_plain_time_and_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_with_timezone_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_with_with_provider(void) { abort(); }
void temporal_rs_ZonedDateTime_year(void) { abort(); }
void temporal_rs_ZonedDateTime_year_of_week(void) { abort(); }
